<a href="https://colab.research.google.com/github/BarryLiu-97/Tensorflow-Tutorial/blob/master/basic/tf_exp_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 机器学习中的一些名词
数据集 data set = 样本集 sample set  
样本 sample  
属性 attribute = 特征 feature  
标记/标签 label  
模型/假设 hypothesis = 学习器 leaner (即估计函数)  
真相/真实 ground truth  
__解析解__：根据严格推导和计算得到，为方程的精确解，可以在任意精度下满足方程  
__数值解__：通过近似计算得到的解，能够在给定的精度下满足方程
__方向导数__：函数沿着某一个方向的变化率  
梯度：模为方向导数的最大值，方向为最大方向导数的方向  
函数在某个点的梯度就是函数在这个点沿着这个方向的变化率最大  
梯度下降法就是沿着最陡，即该方向变化率最大的方向移动  
机器学习中只要能够把损失函数描述成凸函数，就一定可以采用梯度下降法，以最快的速度更新权值向量w,找到使损失函数达到最小值点的位置。  
超参数会影响模型的训练。  
 



# 可训练变量Variable
- __tf.Variable__
 - 对Tensor对象进一步封装
 - 在模型训练过程中自动记录梯度信息，由算法自动优化其取值  
 - 可以被训练的变量  
 - 在机器学习中作为模型参数  
tf.Variable(initial, value, dtype)


In [0]:
import tensorflow as tf
import numpy as np

In [3]:
tf.Variable(3)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [7]:
tf.Variable(3.)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [5]:
tf.Variable([1,2])

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [6]:
tf.Variable(np.array([1,2]))

<tf.Variable 'Variable:0' shape=(2,) dtype=int64, numpy=array([1, 2])>

In [9]:
tf.Variable(tf.constant([[1,2],[3,4]]))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
tf.Variable(tf.zeros([2,3]))

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [11]:
tf.Variable(tf.random.normal([2,2]))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.3632095 ,  0.08037858],
       [-0.85741067,  0.83306426]], dtype=float32)>

In [15]:
x = tf.Variable((1,2))
x

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [16]:
print(x.shape,'\n',x.dtype,'\n',x.numpy)

(2,) 
 <dtype: 'int32'> 
 <bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>>


In [17]:
x.trainable   #判断该数据是否可训练

True

In [18]:
type(x)  

tensorflow.python.ops.resource_variable_ops.ResourceVariable

__可训练变量赋值__  
对象名.assign()  
对象名.assign_add() 加法赋值  
对象名.assign_sub() 减法赋值  

In [0]:
x = tf.Variable([1,2])
x

In [24]:
x.assign([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([3, 4], dtype=int32)>

In [21]:
x.assign_add([1,1])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [26]:
x.assign_sub([2,2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

Tensor对象本身没有assign属性，所以使用过程中要注意对象类型  
可使用isinstance()函数进行判断

In [28]:
a = tf.range(5)
x = tf.Variable(a)
print(isinstance(x,tf.Tensor),'\n',isinstance(x,tf.Variable))

False 
 True


In [29]:
print(isinstance(a,tf.Tensor),'\n',isinstance(a,tf.Variable))

True 
 False
