<a href="https://colab.research.google.com/github/BarryLiu-97/Tensorflow-Tutorial/blob/master/basic/tf_exp_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 部分采样


In [0]:
import tensorflow as tf
import numpy as np

## 索引和切片
与numpy几乎一样
### 索引
与numpy方法一致
### 切片
起始位置：结束位置：步长  
__前闭后开__

In [2]:
a = tf.range(10)
a[::]

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [3]:
a[::2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [11]:
a[1::2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [7]:
a[::-2]  #步长为负数，表示倒序

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([9, 7, 5, 3, 1], dtype=int32)>

### 二维张量切片
维度之间用逗号隔开  
：：，：：  

In [0]:
Train_URL = 'http://download.tensorflow.org/data/iris_training.csv'
train_path = tf.keras.utils.get_file(Train_URL.split('/')[-1], Train_URL)

In [26]:
import pandas as pd
df_iris = pd.read_csv(train_path)
np_iris = np.array(df_iris)
iris = tf.convert_to_tensor(np_iris)
print(iris.shape)
print(df_iris)

(120, 5)
     120    4  setosa  versicolor  virginica
0    6.4  2.8     5.6         2.2          2
1    5.0  2.3     3.3         1.0          1
2    4.9  2.5     4.5         1.7          2
3    4.9  3.1     1.5         0.1          0
4    5.7  3.8     1.7         0.3          0
..   ...  ...     ...         ...        ...
115  5.5  2.6     4.4         1.2          1
116  5.7  3.0     4.2         1.2          1
117  4.4  2.9     1.4         0.2          0
118  4.8  3.0     1.4         0.1          0
119  5.5  2.4     3.7         1.0          1

[120 rows x 5 columns]


In [27]:
iris[0,::]   #第一个列表的所有属性

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([6.4, 2.8, 5.6, 2.2, 2. ])>

In [28]:
iris[0:5,0:4]

<tf.Tensor: shape=(5, 4), dtype=float64, numpy=
array([[6.4, 2.8, 5.6, 2.2],
       [5. , 2.3, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 3.8, 1.7, 0.3]])>

In [30]:
iris[:,0]  #所有样本的第一个属性  两个::可省略为一个:

<tf.Tensor: shape=(120,), dtype=float64, numpy=
array([6.4, 5. , 4.9, 4.9, 5.7, 4.4, 5.4, 6.9, 6.7, 5.1, 5.2, 6.9, 5.8,
       5.4, 7.7, 6.3, 6.8, 7.6, 6.4, 5.7, 6.7, 6.4, 5.4, 6.1, 7.2, 5.2,
       5.8, 5.9, 5.4, 6.7, 6.3, 5.1, 6.4, 6.8, 6.2, 6.9, 6.5, 5.8, 5.1,
       4.8, 7.9, 5.8, 6.7, 5.1, 4.7, 6. , 4.8, 7.7, 4.6, 7.2, 5. , 6.6,
       6.1, 5. , 7. , 6. , 7.4, 5.8, 6.2, 5. , 5.6, 6.7, 6.3, 6.4, 6.2,
       7.3, 4.4, 7.2, 6.5, 5. , 4.7, 6.6, 5.5, 7.7, 6.1, 4.9, 5.5, 5.7,
       6. , 6.4, 5.4, 6.1, 6.5, 5.6, 6.3, 4.9, 6.8, 5.7, 6. , 5. , 6.5,
       6.1, 5.1, 4.6, 6.5, 4.6, 4.6, 7.7, 5.9, 5.1, 4.9, 4.9, 4.5, 5.8,
       5. , 5.2, 5.3, 5. , 5.6, 4.8, 6.3, 5.7, 5. , 6.3, 5. , 5.5, 5.7,
       4.4, 4.8, 5.5])>

### 三维张量切片
__手写数字数据集MNIST__ (60000,28,28)  
第一个维度表示图片张数，即样本数  
后两个维度为图片大小   
__单张彩色图片lena__ (512,512,3)  
lena(:,:,0)表示R通道图片
lena(:,:,1)表示G通道图片
### 四维张量切片-多张彩色图片
如(4,512,512,3)，表示有四张
image[0,:,:,0]第一张图片的R通道
image[0:2,:,:,0]第一张图片的R通道

## 数据提取

切片都是连续的或者有规律的采样  
- __tf.gather()__  
用一个索引列表，将给定张量中，对应索引值的元素提取出来  
gather(params, indices, axis) 
params:索引张量  
axis:进行采样的轴  
indices:索引列表   

In [32]:
a = tf.range(5)
tf.gather(a,indices=[0,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 2, 3], dtype=int32)>

In [35]:
a = tf.range(20)
b = tf.reshape(a, (4,5))
b

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]], dtype=int32)>

In [42]:
tf.gather(b,axis=0,indices=[0,2,3])  

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]], dtype=int32)>

In [49]:
tf.gather(b, indices=[0,2,3], axis=1)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  2,  3],
       [ 5,  7,  8],
       [10, 12, 13],
       [15, 17, 18]], dtype=int32)>

- __tf.gather_nd() 同时采样多个点__  

In [51]:
b

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]], dtype=int32)>

In [50]:
tf.gather_nd(b,[[0,0],[1,1],[2,3]])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 0,  6, 13], dtype=int32)>

In [53]:
print(b[0,0],'\n',b[1,1],'\n',b[2,3])

tf.Tensor(0, shape=(), dtype=int32) 
 tf.Tensor(6, shape=(), dtype=int32) 
 tf.Tensor(13, shape=(), dtype=int32)


__选择采样维度__  
三维张量--彩色图片lena (512,512,3)  
tf.gather_nd(lena, [[0,0],[1,1],[2,3]])  
表示这几个位置的三个通道(即第三个维度)
对于MNIST数据集，因为这是多张图片，(60000,28,28)，tf.gather_nd(mnist,[[0],[1],[2]])表示提取这几张图片