<a href="https://colab.research.google.com/github/BarryLiu-97/Tensorflow-Tutorial/blob/master/basic/tf_exp_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [0]:
print("Eager execution is:", tf.executing_eagerly())   #是否是即时执行  tf2之后都将是即时执行

Eager execution is: True


在Tensorflow2.x中运行Tensorflow1.x

In [0]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Tesndorflow中的"Tensor"表示张量，其实就是多维数组

# Tensorflow-Basic-Tutorial
## 创建张量
- Tensorflow中所有运算都是在张量之间进行
- Numpy数组仅仅作为输入和输出使用，即运算之间通过numpy数组提供数据，再转化为张量进行原酸，之后再使用.numpy进行输出
- 张量可以运行在CPU、GPU、TPU，Numpy只能在CPU中运行  
张量在CPU中运行时，与Numpy共享同一段内存，只是读出和理解的方式不同。  
当张量在GPU中运行时，将内存中的Numpy数组的内容拷贝到显存中进行高速运算。  
此时用Numpy方法读取值，需要从显存中拷贝一份到内存中，再以Numpy的方式输出。
### 创建Tensor对象
张量由Tensor类实现，每个张量都是一个Tensor对象  
- __tf.constant()函数：创建张量__  
tf.constant(value, dtype, shape) 


    value:数字/Python列表/Numpy数组   
    dtype:元素的数据类型 
    shape:数据的形状  

In [0]:
import tensorflow as tf

In [0]:
a = tf.constant([[1,2],[3,4]])

tensorflow中的张量是对numpy的封装，所有张量可以通过.numpy()方式获得numpy数组

In [0]:
print(a.numpy())
print(type(a))
print(a)   #没有了<...>，因为这是python的输出

[[1 2]
 [3 4]]
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


张量也可以是一个数字

In [0]:
tf.constant(1.0)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

可见shape=()，表示零维，即一个数字

In [0]:
tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

1.0可以省略为1. 浮点数默认为32位，也可以自定义,注意要加上tf., 表示是tf中的数据类型


In [0]:
tf.constant(1., dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

使用numpy数组创建张量

In [0]:
import numpy as np

In [0]:
tf.constant(np.array([1,2]))

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 2])>

numpy在创建浮点数数组时默认64位在使用numpy数组创建tensor时同时页会接收其数据类型，故也为64位浮点数

In [0]:
tf.constant(np.array([1.0,2.0]))

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1., 2.])>

在绝大多数情况下32位浮点数已够用，所以建议自定义为float32

In [0]:
tf.constant(np.array([1.0,2.0]),dtype=tf.float32)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

- __tf.cast()函数 改变张量中元素的数据类型__  
tf.cast(x, dtype)

In [0]:
a = tf.constant(np.array([1,2]))
b = tf.cast(a, dtype=tf.float32)
b.dtype

tf.float32

精度转换一般是低精度向高精度转换，否则可能因为数据溢出得到错误的结果

In [0]:
a = tf.constant(123456789, dtype=tf.int32)
tf.cast(a, tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

constant的value参数还可为布尔型或者字符串

In [0]:
tf.constant(True)

可通过tf.cast()函数将布尔型与整型相互转换

In [0]:
a = tf.constant([True, False])
tf.cast(a, tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0], dtype=int32)>

In [0]:
a = tf.constant([-1,0,1,2])
tf.cast(a, tf.bool)  #非零为trye

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

In [0]:
tf.constant('hello')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

b表示字节串，因为python3中字符串默认unicode编码

- __tf.convert_to_tensor()函数 创建张量__   
tf.convert_to_tensor(数组/列表/数字/布尔值/字符串)

In [0]:
na = np.arange(12).reshape(3,4)
ta = tf.convert_to_tensor(na)

In [0]:
type(na)

numpy.ndarray

In [0]:
type(ta)

tensorflow.python.framework.ops.EagerTensor

- __is_tensor()函数 判断数据对象是否为张量__

In [0]:
tf.is_tensor(ta)

True

In [0]:
tf.is_tensor(na)

False

- __isinstance()函数 判断是否为tensor对象__



In [0]:
isinstance(ta,tf.Tensor)

True

In [0]:
isinstance(na,np.ndarray)

True

类似于Numpy,Tensorflow中也可以直接生成一些特殊的张量
- 全0张量
- 全1张量
- 所有元素值都相同的张量
- 元素取值符合某种随机分布的张量

- __创建全0张量和全1张量__  
tf.zeros(shape, dtype=tf.float32)  
tf.ones(shape, dtype=tf.float32)  
二者用法完全相同

In [6]:
tf.ones(shape=(2,1)).numpy()

array([[1.],
       [1.]], dtype=float32)

In [5]:
tf.ones([6]).numpy()

array([1., 1., 1., 1., 1., 1.], dtype=float32)

In [7]:
tf.ones([2,3],tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

- __tf.fill()函数 创建元素值都相同的张量__  
tf.fill(dims, value)

In [9]:
tf.fill([2,3],9)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)>

数值类型由设置的数字决定，如9则为int32，9.0则为float32

In [10]:
tf.fill([2,3],9.0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[9., 9., 9.],
       [9., 9., 9.]], dtype=float32)>


- __tf.constant()函数 创建元素值相同的张量__

In [11]:
tf.constant(9,shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)>

In [14]:
tf.fill(dims=[2,3],value=9)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)>

- __tf.random.normal()函数 创建随机数张量--正态分布__  
tf.ranndom.normal(shape, mean, stddev, dtype)  
默认标准正态分布，均值为0标准差为1

In [15]:
tf.random.normal([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.2579081 ,  0.66722006,  1.2525816 ],
       [-0.11997709, -0.6495289 ,  1.7353811 ]], dtype=float32)>

In [16]:
tf.random.normal([3,3,3], mean=0.0, stddev=2.0)  #创建三维张量

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-1.2629505 , -0.6973741 ,  0.71443063],
        [ 1.836137  ,  3.414606  ,  2.401567  ],
        [-0.03277259,  4.787197  , -0.4700112 ]],

       [[ 0.8261258 ,  0.38950595,  3.118399  ],
        [-0.41610304,  1.852355  ,  0.09665768],
        [ 0.3899136 ,  0.2673345 ,  1.3338954 ]],

       [[-0.28611094,  1.0075696 , -0.50876033],
        [-1.7829444 , -0.35610813,  1.8905334 ],
        [-1.1053185 ,  1.7513752 , -1.345811  ]]], dtype=float32)>

- __tf.randomm_truncated_normal()函数 创建随机数张量--截断正态分布__
tf.random.truncated_normal(shape, mean, stddev, dtype)  
返回一个截断的正态分布  
截断的标准是2倍的标准差  
防止张量中出现与其他数据相差过大的数值  
eg.当均值为0标准差为1时，
使用tf.truncated_normal，不可能出现区间[-2,2]以外的点  
使用tf.random.normal则有可能

- __tf.random.set_seed()函数 设置随机种子__




In [17]:
tf.random.set_seed(8)
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.2074401 , -0.7452463 ],
       [ 0.6908678 , -0.76359874]], dtype=float32)>

In [18]:
tf.random.set_seed(8)
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.2074401 , -0.7452463 ],
       [ 0.6908678 , -0.76359874]], dtype=float32)>

两次产生的随机张量相同

- __tf.random.uniform()函数 创建均匀分布张量__  
tf.random.uniform(shape, minval, maxval, dtype)  
[minval, maxval) 区间前闭后开  
张量元素服从[minval, maxval)的均匀分布

In [19]:
tf.random.uniform(shape=(3,3), minval=0, maxval=10, dtype='int32')

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 8, 3],
       [9, 5, 1],
       [8, 6, 1]], dtype=int32)>

- __tf.random.shuffle()函数 随机打乱__  
随机将张量根据第一维打乱,即只打乱第一维，其他维度根据第一维度进行变化  
注意，python中都是列向量  
1，3，5才是第一维度

In [20]:
x = tf.constant([[1,2],[3,4],[5,6]])
tf.random.shuffle(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

In [22]:
y = [1,2,3,4,5,6]
tf.random.shuffle(y)  #结果返回一个张量

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 5, 4, 2, 3, 6], dtype=int32)>

In [24]:
import numpy as np
z = np.arange(5)
tf.random.shuffle(z)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 1, 2, 4, 0])>

- __tf.range()函数 创建序列__  
tf.range(start, limit, delta=1, dtype)
创建一个整型的数字序列，区间左闭右开  
delta表示步长

In [26]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [27]:
tf.range(10,delta=2)  #创建偶数序列，因为起始值为0

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [29]:
tf.range(1,10,delta=2)  #创建奇数序列

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

## Tensor对象的属性
ndim:维度  
shape:形状  
dtype:数据类型

In [30]:
a = tf.constant([[1,2],[3,4]])
print('ndim', a.ndim)
print('shape', a.shape)
print('dtype', a.dtype)

ndim 2
shape (2, 2)
dtype <dtype: 'int32'>


- __tf.shape() tf.size() tf.rank()__  
分别是形状、元素总数和维度

In [31]:
print(tf.shape(a))
print(tf.size(a))
print(tf.rank(a))

tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
