<a href="https://colab.research.google.com/github/BarryLiu-97/Tensorflow-Tutorial/blob/master/tf_exp_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%tensorflow_version 2.x
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [4]:
print("Eager execution is:", tf.executing_eagerly())

Eager execution is: True


#在Tensorflow2.x中运行Tensorflow1.x

In [0]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Tesndorflow中的"Tensor"表示张量，其实就是多维数组

# Tensorflow-Tutorial
## 创建张量
### 创建Tensor对象
张量由Tensor类实现，每个张量都是一个Tensor对象  
- __tf.constant()函数：创建张量__
tf.constant(value, dtype, shape) 


    value:数字/Python列表/Numpy数组   
    dtype:元素的数据类型 
    shape:数据的形状  

In [0]:
import tensorflow as tf

In [0]:
a = tf.constant([[1,2],[3,4]])

tensorflow中的张量是对numpy的封装，所有张量可以通过.numpy()方式获得numpy数组

In [10]:
print(a.numpy())
print(type(a))
print(a)   #没有了<...>，因为这是python的输出

[[1 2]
 [3 4]]
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


张量也可以是一个数字

In [11]:
tf.constant(1.0)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

可见shape=()，表示零维，即一个数字

In [12]:
tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

1.0可以省略为1. 浮点数默认为32位，也可以自定义,注意要加上tf., 表示是tf中的数据类型


In [13]:
tf.constant(1., dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

使用numpy数组创建张量

In [0]:
import numpy as np

In [15]:
tf.constant(np.array([1,2]))

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 2])>

numpy在创建浮点数数组时默认64位在使用numpy数组创建tensor时同时页会接收其数据类型，故也为64位浮点数

In [18]:
tf.constant(np.array([1.0,2.0]))

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1., 2.])>

在绝大多数情况下32位浮点数已够用，所以建议自定义为float32

In [20]:
tf.constant(np.array([1.0,2.0]),dtype=tf.float32)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

tf.cast()函数 改变张量中元素的数据类型

|tf.cast(x, dtype)|
|------------------|

In [22]:
a = tf.constant(np.array([1,2]))
b = tf.cast(a, dtype=tf.float32)
b.dtype

tf.float32

精度转换一般是低精度向高精度转换，否则可能因为数据溢出得到错误的结果

In [24]:
a = tf.constant(123456789, dtype=tf.int32)
tf.cast(a, tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

constant的value参数还可为布尔型或者字符串

In [0]:
tf.constant(True)

可通过tf.cast()函数将布尔型与整型相互转换

In [25]:
a = tf.constant([True, False])
tf.cast(a, tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0], dtype=int32)>

In [26]:
a = tf.constant([-1,0,1,2])
tf.cast(a, tf.bool)  #非零为trye

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

In [28]:
tf.constant('hello')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

b表示字节串，因为python3中字符串默认unicode编码

- tf.convert_to_tensor()函数  创建张量

|tf.convert_to_tensor(数组/列表/数字/布尔值/字符串)|
|-----------|

In [0]:
na = np.arange(12).reshape(3,4)
ta = tf.convert_to_tensor(na)

In [30]:
type(na)

numpy.ndarray

In [31]:
type(ta)

tensorflow.python.framework.ops.EagerTensor

- is_tensor()函数 判断数据对象是否为张量

In [32]:
tf.is_tensor(ta)

True

In [33]:
tf.is_tensor(na)

False

- isinstance()函数 判断是否为tensor对象



In [34]:
isinstance(ta,tf.Tensor)

True

In [36]:
isinstance(na,np.ndarray)

True