<a href="https://colab.research.google.com/github/BarryLiu-97/Tensorflow-Tutorial/blob/master/basic/tf_exp_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 维度变换

In [0]:
import tensorflow as tf
import numpy as np

- __tf.reshape()__ 改变张量的形状
tf.reshape(tensor, shape)

In [3]:
a = tf.range(24)
b = tf.reshape(a, (2,3,4))
b

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

先用numpy创建需要的三维数组，再使用tf.constant转换为张量

In [6]:
tf.constant(np.arange(24).reshape(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

shape中有-1表示该维度长度未知，需要经过元素总个数与其他维度的参数自动推导出来

In [7]:
tf.reshape(b,(4,-1))

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]], dtype=int32)>

这些方式仅仅改变了张量的视图，在内存中的存储仍然是以连续的一维数组的方式进行存储。

## 多维张量的轴
多维张量的轴：多维张量的每一个维度叫做一个轴  

|shape|(4,)|(3,4)|(2,3,4)|
|---|---|---|---|
|axis|0|0,1|0,1,2或者-3，-2，-1|



## 增加和删除维度
增加和删除维度只是改变了张量的视图，在内存中的存储仍然是以连续的一维数组的方式进行存储。
- __tf.expand_dims(input, axis) 增加维度__  
input:输入的张量
axis:指明要在哪个轴上增加维度，该增加的维度长度为1，即只有一个元素

In [15]:
t = tf.constant([1,2])  #一维
t

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [12]:
t1= tf.expand_dims(t, 1)
t1.shape

TensorShape([2, 1])

In [10]:
t1

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]], dtype=int32)>

In [14]:
t2 = tf.expand_dims(t, 0)
t2.shape

TensorShape([1, 2])

In [16]:
t2

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>

t2看似与t一样实则不同，t2是一个二维张量

In [17]:
t3 = tf.expand_dims(t, -1)
t3

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]], dtype=int32)>

In [18]:
a = tf.range(24)
b = tf.reshape(a, (2,3,4))
b.shape

TensorShape([2, 3, 4])

In [22]:
b1 = tf.expand_dims(b, 0)  #在第一维增加一个维度
b2 = tf.expand_dims(b, 1)
b3 = tf.expand_dims(b, 2)
b4 = tf.expand_dims(b, 3)
print(b1.shape)
print(b2.shape)
print(b3.shape)
print(b4.shape)

(1, 2, 3, 4)
(2, 1, 3, 4)
(2, 3, 1, 4)
(2, 3, 4, 1)


- __tf.squeeze() 删除维度__  
tf.squeeze(input, axis)  
只能删除长度为1的维度
axis默认为删除所有长度为1的轴

- __tf.transpose() 交换维度__  
tf.transpose(a, perm)  
对于二维张量来说就是转置
perm表示张量中各个轴的顺序

In [25]:
x = tf.constant([[1,2,3],[4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [27]:
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [28]:
tf.transpose(x, perm=[1,0])  #shape变为了(3，2),即进行了转置

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [41]:
a = tf.range(24)
b = tf.reshape(a, (2,3,4))
b.shape

TensorShape([2, 3, 4])

In [42]:
b

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [30]:
tf.transpose(b, (1,0,2))

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]], dtype=int32)>

图像中多用四阶张量，含义分别为批量示例、图像高度（行数）、图像宽度（列数）、图像通道数

## 拼接与分割张量
拼接与分割张量也仅是改变视图，不会影响存储方式  
- __tf.concat() 拼接张量__  
tf.concat(tensors, axis)   
tesnors是一个列表，包含所有要拼接的张量  
axis表示在哪个维度进行拼接

In [0]:
t1 = [[1,2,3],[1,2,3]]
t2 = [[2,3,4],[2,3,4]]

In [44]:
tf.concat([t1,t2],0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [2, 3, 4],
       [2, 3, 4]], dtype=int32)>

In [45]:
tf.concat([t1,t2],1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 2, 3, 4],
       [1, 2, 3, 2, 3, 4]], dtype=int32)>

从第二个中括号开始为维度0

- __tf.split() 分割张量__  
tf.split(value, num_or_size_splits, axis=0)  
将一个张量拆分成多个张量，分割后__维度不变__      
value:待分割张量  
axis:按哪个轴分割，默认为0  
num_or_size_splits:分割方案，参数为单个数值时为切割份数；为一个列表时表示是不等长切割，列表中数值表示不同轴的长度


In [47]:
x = tf.range(24)
x = tf.reshape(x, (4,6))
x

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]], dtype=int32)>

In [48]:
tf.split(x,2,0)  #在维度0上分割为两份

[<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]], dtype=int32)>,
 <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]], dtype=int32)>]

In [50]:
tf.split(x,[1,2,1],0)

[<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[0, 1, 2, 3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]], dtype=int32)>,
 <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[18, 19, 20, 21, 22, 23]], dtype=int32)>]

In [52]:
tf.split(x,[2,4],1)

[<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]], dtype=int32)>, <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[ 2,  3,  4,  5],
        [ 8,  9, 10, 11],
        [14, 15, 16, 17],
        [20, 21, 22, 23]], dtype=int32)>]

## 堆叠和分解
- __tf.stack(values, axis) 张量堆叠__  
tf.stack(values, axis)  
合并张量时，创建一个新的维度   
axis表示在哪个轴进行堆叠

In [55]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])
x,y

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>)

In [54]:
tf.stack((x,y),axis=0)  

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>



|1|4|
|---|---| 
|2|5|
|3|6|  

In [58]:
tf.stack((x,y),axis=1)  

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

|1|2|3|
|---|---|---|
|4|5|6|

__难点！__  
tf.stack与tf.concat的关键区别在于concat不会增加维度而stack会  
故使用tf.stack时，会将原张量增加一个维度，然后在这个新增加的维度基础上的axis进行拼接。如axis=1时候，x先增加一个维度变为[[1,2,3]],y变为[[4,5,6]],1所在维度为第二维度，即axis=1，与4是同意维度，故1和4拼接，2与5，3与6。张量中逗号在维度分析中有着重要作用。axis=1时，1为轴2即第二个个维度，所以1单独为一个整体，与2，3并列，1在b中对应位置的同维度为4。

- __tf.unstack() 分解张量__  
tf.unstack(values, axis)  


In [66]:
c = tf.constant([[[1,2,3],
         [4,5,6],
         [7,8,9]],
         [[11,12,13],
          [14,15,16],
          [17,18,19]]])
c

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]], dtype=int32)>

In [68]:
tf.unstack(c, axis=0)

[<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]], dtype=int32)>]

In [67]:
tf.unstack(c, axis=1)

[<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [11, 12, 13]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 4,  5,  6],
        [14, 15, 16]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [17, 18, 19]], dtype=int32)>]

axis=1,表示第二个维度消失，[1,2,3]在第二个维度，与[11,12,13]相对应，故[1,2,3]与[11,12,13]结合组成一个新向量分离出来。